import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "motohub",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
function Topnav() {
  return (
    <nav className="flex w-full items-center justify-between p-4 text-l bg-black/5 font-semibold">
      <a href="/">
        <img src="https://5o49s9j5d8.ufs.sh/f/AYfuaRWx9vQljOUCg6DxhMk4zdpDq71vaywFfGsnCHmclKZU" alt="Home" className="h-10 w-10" />
      </a>
      <a>
        <div>MOTOHUB</div>
      </a>
      <a href="/about">About</a>
    </nav>
  );
}



export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Topnav />
        {children}
        </body>
    </html>
  );
}
