import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";


export const metadata: Metadata = {
  title: "motohub",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


function Topnav() {
  return (
    <nav className="flex w-full items-center justify-between p-4 text-l bg-black font-semibold">
  <a href="/">Home</a>
  <div>
    <img src="src/app/imgs/motohub.png"  className="h-10" /> 
  </div>
  <a href="/about">About</a>
</nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Topnav />
        {children}
        </body>
    </html>
  );
}
